# Where to read files from (relative to parent mono-repo)
assetDir: portfolio/assets
contentDir: portfolio/content
dataDir: portfolio/data
layoutDir: portfolio/layouts
resourceDir: portfolio
staticDir:
  - shared/static
  - portfolio/static
