# Where to read files from (relative to parent mono-repo)
assetDir: portfolio/assets
contentDir: portfolio/content
dataDir: portfolio/data
layoutDir: portfolio/layouts
staticDir:
  - shared/assets
  - portfolio/static

# Write hugo_stats.json to use for CSS post-processing
build:
  writeStats: true

# We don't want/need these content types
disableKinds:
  - RSS
  - sitemap
  - taxonomy
  - term

# We explicitly don't want taxonomies (https://gohugo.io/content-management/taxonomies/)
ignoreErrors:
  - error-disable-taxonomy

# Minimize HTML
minify:
  minifyOutput: true

# Available at $.Site.Params.<key> in templates
params:
  fingerprint:
    enabled: true
    algorithm: md5 # sha512 (largest), sha384, sha256 (default), or md5 (smallest)
  scss:
    outputStyle: compressed # expanded (largest), nested (default), compact, or compressed (smallest)
