# https://fly.io/docs/reference/configuration/

app = 'm0b1d3v'
primary_region = 'atl'

[build]
dockerfile = 'Dockerfile'
ignorefile = '.dockerignore'
build-target = 'production'

[deploy]
strategy = 'rolling'

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[mounts]
source = "m0b1d3v_caddy_data"
destination = "/data"
initial_size = '1gb'

[[vm]]
size = 'shared-cpu-1x'
memory = '256mb'
