# Write hugo_stats.json to use for CSS post-processing
build:
  writeStats: false

# Minimize HTML
minify:
  minifyOutput: false

# Available at $.Site.Params.<key> in templates
params:
  fingerprint:
    enabled: false
  scss:
    outputStyle: expanded # expanded (largest), nested (default), compact, or compressed (smallest)
  ts:
    minify: false
    target: esnext # esnext (default, latest), es2020, es2019, ..., es2015 (aka es6), es5 (earliest)
