# fly.toml app configuration file generated for m0b1d3v on 2025-05-24T20:06:47-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'm0b1d3v'
primary_region = 'atl'

[build]
  dockerfile = 'Dockerfile'
  ignorefile = '.dockerignore'
  build-target = 'production'

[deploy]
  strategy = 'rolling'

[[mounts]]
  source = 'm0b1d3v_caddy_data'
  destination = '/data'
  initial_size = '1gb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
