# Hostname root
baseURL: "https://qa.mobiusk.com/"

# Minimize HTML
minify:
  minifyOutput: true

# Available at $.Site.Params.<key> in templates
params:
  css:
    outputStyle: compressed
  fingerprint:
    enabled: true
