# Hostname root
baseURL: "https://mobiusk.com/"

# Minimize HTML
minify:
  minifyOutput: true

# What to prepend to links to potentially make them load from a CDN
params:
  css:
    outputStyle: compressed
  fingerprint:
    enabled: true
